const products= [
    // {
    //   name: 'Montre pasha de cartier',
    //   slug: 'Montre-pasha-de-cartier',
    //   category: 'watches',
    //   images: ['1.webp','2.webp','3.webp'],
    //   price: "129.000",
    //   brand: 'cartier',
    //   countInStock: 20,
    //   description: 'Mouvement mécanique à remontage automatique 1847 MC',
    // },
    {
        name: 'Montre ballon bleu de cartier',
        slug: 'Montre-ballon-bleu-de-cartier',
        category: 'watches',
        images: ['4.webp'],
        price: "4.999",
        brand: 'cartier',
        countInStock: 20,
        description: 'Mouvement mécanique à remontage automatique 1847 MC',
      },
      {
        name: 'Montre santos de cartier',
        slug: 'Montre-santos-de-cartier',
        category: 'watches',
        images: ['7.webp','8.webp','9.webp'],
        price: "6.200",
        brand: 'cartier',
        countInStock: 20,
        description: 'Mouvement mécanique à remontage automatique 1847 MC',
      },
      {
        name: 'Montre pasha de cartier',
        slug: 'Montre-pasha-de-cartier',
        category: 'watches',
        images: ['10.webp','12.webp'],
        price: "69.499",
        brand: 'cartier',
        countInStock: 20,
        description: 'Mouvement mécanique à remontage automatique 1847 MC',
      },
      {
        name: 'Montre tank de cartier',
        slug: 'Montre-tank-de-cartier',
        category: 'watches',
        images: ['5.webp'],
        price: "189.99",
        brand: 'cartier',
        countInStock: 20,
        description: 'Mouvement mécanique à remontage automatique 1847 MC',
      },
      // {
      //   name: 'Capuche fitverse',
      //   slug: 'Capuche-fitverse',
      //   category: 'watches',
      //   images: ['capuche2.JPG'],
      //   price: "24.99",
      //   brand: 'fitverse',
      //   countInStock: 7,
      //   description: 'New Fitverse Hoodie 2024',
      // },
      // {
      //   name: 'Capuche fitverse',
      //   slug: 'Capuche-fitverse',
      //   category: 'watches',
      //   images: ['capuche3.JPG'],
      //   price: "24.99",
      //   brand: 'fitverse',
      //   countInStock: 7,
      //   description: 'New Fitverse Hoodie 2024',
      // },
      // {
      //   name: 'Capuche fitverse',
      //   slug: 'Capuche-fitverse',
      //   category: 'watches',
      //   images: ['fit.JPG'],
      //   price: "24.99",
      //   brand: 'fitverse',
      //   countInStock: 7,
      //   description: 'New Fitverse Hoodie 2024',
      // },
      // {
      //   name: 'Capuche fitverse',
      //   slug: 'Capuche-fitverse',
      //   category: 'watches',
      //   images: ['logo.JPG'],
      //   price: "24.99",
      //   brand: 'fitverse',
      //   countInStock: 7,
      //   description: 'New Fitverse Hoodie 2024',
      // },
      // {
      //   name: 'Capuche fitverse',
      //   slug: 'Capuche-fitverse',
      //   category: 'watches',
      //   images: ['verse logo.JPG'],
      //   price: "24.99",
      //   brand: 'fitverse',
      //   countInStock: 7,
      //   description: 'New Fitverse Hoodie 2024',
      // },
      // {
      //   name: 'Hoodie',
      //   slug: 'Hoodie',
      //   category: 'men',
      //   images: ['1.jpeg','2.jpeg','3.jpeg','4.jpeg'],
      //   price: "29.99",
      //   brand: 'fitverse',
      //   countInStock: 7,
      //   description: 'New Fitverse Hoodie 2024',
      // },
  ]

  module.exports = products